### ISSUE TITLE
Sorting reference side-nav

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#125]
Currently, the side reference in the sand box does not sort symbols. It would be easier navigating through them if they were.

As a bonus, not losing scroll position when closing and re-opening the side reference would be more comfortable. Especially since its not possible looking both at the reference and typing in the sandbox at once.

**Comment by helins** [comment]
At least sorting the reference would be appreciated for alpha if it's just a quick fix, if you can manage :)

**Comment by pedrorgirardi** [comment]
Hi @helins . How is it not sorted?

**Comment by pedrorgirardi** [comment]
Commit 87cfbad604ef931b4935d1460e7733724b674cb2 fixes the sorting.

It seems there is an API to preserve the state of the Transition component - Side nav - but I haven't tried it yet.
