### ISSUE TITLE
Mobile-friendly layout of landing page

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#127]
Let us rely on this issue for tracking changes that needs to be done for making the landing page mobile-friendly.

Please post pictures to make your point. You can emulate mobile view on desktop in Chrome and Firefox.

![Screenshot from 2021-07-21 16-55-18](https://user-images.githubusercontent.com/17478152/126512784-275b3ba9-64ca-4e73-a76d-5e79bf657812.png)

- Top menu should turn into some sort of hamburger menu + not copycat footer (see #126 )
- Page `max-width` should be set on main content. Currently, the top menu overflows and you can actually scroll to the right.
- Padding left and right of first section.

![Screenshot from 2021-07-21 16-56-14](https://user-images.githubusercontent.com/17478152/126512813-a1ae3e1c-1f3f-4699-bd27-8a22ef072bc6.png)

- Sections `max-width` should depend on text
- Picture should probably be centered.
- Bullet point size should be in `rem`, proportional to text
- All of those apply to further sections

![Screenshot from 2021-07-21 16-56-19](https://user-images.githubusercontent.com/17478152/126512834-37a82d41-fb99-4157-a350-96162db80dcb.png)

- Picture should flow like in section above

**Comment by helins** [comment]
Thanks for the recent changes, the home page is looking a lot better!

Just a quick note that tapping on the "Team" link does not scroll the page to the top, so it looks like nothing happened until you scroll up yourself.

**Comment by pedrorgirardi** [comment]
Thanks @helins. I will have a look.

**Comment by pedrorgirardi** [comment]
@helins I made a small change to fix that.
