### ISSUE TITLE
Anchor footer to the bottom

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#135]
Thanks for the update!

Switching from one section (aka "heading") to another is janky because content disappears, footer momentarily jumps to the top, and then back to the bottom when new content reappears.

Overall we should find a way to anchor the footer to the very bottom because right now, it simply follows content and looks out of place when there is white space below it:

![Screenshot from 2021-07-29 12-10-51](https://user-images.githubusercontent.com/17478152/127476081-6baef61d-e326-4981-b905-654d658a1625.png)

![Screenshot from 2021-07-29 12-25-05](https://user-images.githubusercontent.com/17478152/127476129-ff46c1e9-aecb-45e1-b625-2a4237518bd6.png)

Two alternatives I see :

a) `:min-height` of content area is `100vh - $nav-bar-height` ; occupies whole height even when blank (taking into account the top nav bar) ; you should never see the footer jumping and as soon as you scroll, you can see it.

a) idem but `:min-height` is maybe `50vh` or `60vh` ; you might see the footer jumping, at least less than before being there is a mininimum height for the content (even when blank), but it might look better than (a)

If Tailwind doesn't allow it, it's perfectly fine to add a couple inline styles :)

**Comment by pedrorgirardi** [comment]
Thanks @helins !
