### ISSUE TITLE
Removing old addresses references

### ISSUE THREAD

**Issue by miguel-depaz** [Convex-Dev/convex-web#140]
2 MD files still have old references to "long address" format. Content to be updated with right format
getting_started.md
glossary.md

![image](https://user-images.githubusercontent.com/61572212/127853034-c9699f70-390f-4b39-95d1-eadac94002f6.png)

**Comment by pedrorgirardi** [comment]
Fixed the address, added a Sandbox image and made some minor changes in the examples.
