### ISSUE TITLE
Better Faucet Details description. Amount and unit coins given for test accounts

### ISSUE THREAD

**Issue by miguel-depaz** [Convex-Dev/convex-web#141]
![image](https://user-images.githubusercontent.com/61572212/127853383-17f18cf2-2978-4d30-8a40-d5ffd2c386f6.png)

**Comment by mikera** [comment]
@miguel-depaz  can you be more specific than "Better"? What wording do you recommend?

**Comment by mikera** [comment]
I suggest clarifying that the amount is always copper coins (the lowest denomination)

**Comment by miguel-depaz** [comment]
We should be very clear that a test account gets: XYZ Copper coins (eg. 10,000 cxv? or 100,000,000 copper coins) across mobile app and website UI.

**Comment by miguel-depaz** [comment]
What is the default amount we grant for each faucet? Given large amounts in the hundredths thousands and millions might look like we are printing machine platform? (which can have a negative impact). Are we ok, to give just few coins to developers to run some smart contracts and tests?).

All those details are not very clear, or at least I couldn't find all relevant information on how it works the faucet allocation, units, default, maximum refill, etc

**Comment by mikera** [comment]
This is a developer API, not a User Interface. Developers should be able to handle the quantity conversions.

The Client API doesn't specify what amounts the server may or may not honour, though we should describe what response the server should give if the amount requested is not possible.
