### ISSUE TITLE
UI/UX: Add Convex Lisp specific syntax highlighter.

### ISSUE THREAD

**Issue by miguel-depaz** [Convex-Dev/convex-web#149]
We should improve the UI experience by creating our own highlighter.

![image](https://user-images.githubusercontent.com/61572212/128002440-e83e3676-9e8c-40fb-a981-65e5dbd3129c.png)

**Comment by mikera** [comment]
I think it is possible to get markdown to render these as Clojure?

**Comment by pedrorgirardi** [comment]
I misunderstood this when @miguel-depaz explained it to me.

Yes, we need a Convex Lisp grammar for our editor, we're currently using a Clojure grammar, but the issue with the glossary can be fixed if a minor change in the code block to specify the language.

I added `clojure` to **Account Key** and **Address** examples:

![Screen Shot 2021-08-04 at 13 36 49](https://user-images.githubusercontent.com/585191/128133873-02623f7c-037c-4d26-b668-1b203fc39ca7.png)
![Screen Shot 2021-08-04 at 13 36 54](https://user-images.githubusercontent.com/585191/128133880-829b19be-3e1c-4bc0-83d5-3563f15a7140.png)

Can this issue be closed @miguel-depaz?
