### ISSUE TITLE
Key advantages on landing page

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#153]
Some time ago, @mikera shared the idea of having something like this on the landing page:

![unknown](https://user-images.githubusercontent.com/17478152/128597048-c0bdba2f-7d88-4822-b266-6f1bec5320ab.png)

Not knowing that, @miguel-depaz is working on something similar asked me to share what he is currently working on (doesn't have access to his laptop right now):

![unknown (1)](https://user-images.githubusercontent.com/17478152/128597079-06598cf7-7216-42a9-a119-2cda434f5dc9.png)
![unknown (2)](https://user-images.githubusercontent.com/17478152/128597082-75fcf172-3276-4cb6-a3b7-d6c5d88cbf8a.png)

I post it here so that we can all sync. Personally, I like the those big plains logos. If we go that direction, question is which color do we settle on: blue, teal, or a mix of both.

**Comment by mikera** [comment]
Yes I would like some key advantages on the landing page beyond what we already have. I could get behind either blue or teal logos as long as the whole page looks OK (though I do want blue as the primary colour)

**Comment by pedrorgirardi** [comment]
@mikera, do you have the images and copy in a document?

**Comment by miguel-depaz** [comment]
Proposed changes to the HP as shown in the enclosed image (experience in Mobile and Desktop). In addition, you can find details on the graphical elements used to design the updates in the zip file.


[New HP Elements.zip](https://github.com/Convex-Dev/convex-web/files/6960285/New.HP.Elements.zip)

![image](https://user-images.githubusercontent.com/61572212/128838055-fd925cde-5f6e-40b5-9722-f3c31956df10.png)
