### ISSUE TITLE
Double horizontal scrolling in the sandbox

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#157]
The scrolling experience was not great when working with large data stretching far right but it was somewhat usable. Unfortunately the experience got worse as you can see on the screenshot. It's a bit hard to describe accurately but in essence everything stretches to the right, with a scroll bar at the the very bottom, but the rendering area has a scroll bar as well. To scroll to the end of the rendering area, you have to actually scroll both bars.

I assume there shouldn't be a bottom scroll bar. Everything bellow the rendering area, input area included, should have a fixed width of 100% without any scrolling.

Is it possible to tweak when objects are displayed on one line or not?

![Screenshot from 2021-08-11 12-07-53](https://user-images.githubusercontent.com/17478152/129011275-e0a93bbd-0dfa-4ef4-ace0-9dfc7ca5fb95.png)

**Comment by pedrorgirardi** [comment]
Fixed by 95445a3fdda4de88b9e0e8829393fb6ecd218bbf
