### ISSUE TITLE
Use  term "actor" instead of "library"

### ISSUE THREAD

**Issue by helins** [Convex-Dev/convex-web#170]
An account being a library or not is almost a point of view rather than clearly defined. These places should use the term "actor" instead of "library" since that is what they are (accounts without keys):

![Screenshot from 2021-09-05 14-37-12](https://user-images.githubusercontent.com/17478152/132127039-b05271e0-292f-4695-a3cd-ddcd573126c2.png)
![Screenshot from 2021-09-05 14-37-29](https://user-images.githubusercontent.com/17478152/132127041-583f93d3-5642-4839-a290-12bd489864d6.png)

**Comment by pedrorgirardi** [comment]
It's a regression introduced when we removed `*exports*` from the environment.

Type, at least initially, could be:
- Library: it's an Actor but it doesn't have exports;
- Actor: if `AccountStatus.isActor` is `true`
- User: if not a library nor an Actor

To fix the `Actor` type, on this page, we need to know if an account has exports. How can we do that @helins @mikera ?

**Comment by mikera** [comment]
Perhaps this could be metadata on the account in the registry?

Alternatively could scan the environment for `:callable?` in the metadata in individual entries. You probably need to do this anyway if analysing the environment, but it might not be such a great idea if displaying a long list...

**Comment by helins** [comment]
Whether an account is technically a library is more of a detail I find. What is most important for the time being is whether it is an actor or not and that's easy, simply check for public key. I wouldn't worry too much about libraries for the time being.

**Comment by pedrorgirardi** [comment]
Fixed by 455d5fd929da2d6f7a6330834d52923aa2ceba66
