### ISSUE TITLE
Sessions not persisting?

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex-web#200]
If I close my Chrome tabs (on windows) but then open conex.world again, I appear to lose all my previous accounts and session data.

It it possible to retain these? e.g. with a session cookie?

**Comment by pedrorgirardi** [comment]
This is strange @mikera . The session has always been persisted, and I just tried on Firefox and Safari - I closed the browser and opened and again, and I can still access my accounts (session).

**Comment by mikera** [comment]
Hmm maybe it was Chrome being too aggressive about blocking cookies?

**Comment by pedrorgirardi** [comment]
I can reproduce on macOS with Chrome.

There's a setting to clear cookies when you close all windows, but mine is disabled, and Google Chrome still clears the cookies when I close the window. It's a bit puzzling. 

<img width="699" alt="Screen Shot 2021-09-18 at 6 43 37 PM" src="https://user-images.githubusercontent.com/585191/133887643-bc108cd1-6cb6-4f26-a9cd-476739ac97d3.png">

**Comment by mikera** [comment]
Will become less urgent once we have the facility to restore an account with an explicit keypair

**Comment by pedrorgirardi** [comment]
If you save your wallet key, you can restore your wallet. It doesn't fix the problem, but at least you don't lose access to your wallet.

**Comment by pedrorgirardi** [comment]
<img width="810" alt="Screen Shot 2021-09-20 at 6 53 20 PM" src="https://user-images.githubusercontent.com/585191/133998180-1437aedc-4bc6-4626-8735-ea629367728b.png">

We are using session cookies so you need to set Chrome to restore your previous sessions on startup:
<img width="729" alt="Screen Shot 2021-09-20 at 6 13 42 PM" src="https://user-images.githubusercontent.com/585191/133998326-75e83a08-4bb7-48c0-a153-0126114997ea.png">

Can you see if this works for you @mikera ?

**Comment by mikera** [comment]
Looking at the ring-session cookie I Chrome I see:

```
Expires
When the browsing session ends
```

Shouldn't that be some future time?

**Comment by pedrorgirardi** [comment]
We can explicitly set the expiration for the cookie, but we need to set it to a distant future since we don't have sign-in, and once the cookie expires, the user will lose their wallet.

Setting the expiration is explicit, and we don't depend on the browser's session behavior, so it seems a better idea @mikera .
