### ISSUE TITLE
Blocks page slow to load

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex-web#202]
The Blocks page (https://convex.world/testnet/blocks) seems slow to load.

Is it possible there is something like an O(n) operation happening here? It should be quick. This would become a problem once the block order gets a lot longer.

**Comment by pedrorgirardi** [comment]
It's not an O(n) operation, but blocks also return its transaction's result. The latest blocks happen to be your game, which in turn happens to have a large result.

These blocks have a payload of about 767 KB: https://convex.world/testnet/blocks?end=15216

I reckon blocks should be lazy? We don't need to download a block's transactions until requested by the user.

**Comment by mikera** [comment]
Not so much about laziness - we just shouldn't be loading any results when simply viewing a list of blocks.
