### ISSUE TITLE
Show docs for macros in Sandbox

### ISSUE THREAD

**Issue by mikera** [Convex-Dev/convex-web#221]
Currently we don't give friendly docs when the user types in the name of a macro on it's own. 

Examples:

```
loop
when-not
asset
```
Ideally, sandbox should show docs when available

**Comment by pedrorgirardi** [comment]
<img width="1066" alt="Screenshot 2023-09-29 at 13 49 37" src="https://github.com/Convex-Dev/convex-web/assets/585191/8946728a-5751-4c50-a969-ae5acd64de69">


@mikera I'm not sure how to lookup metadata for a `convex.core.lang.impl.Fn`; we can do it for a `symbol` and for a `CoreFn` (using its symbol), but I don't know how we can do for a `convex.core.lang.impl.Fn`.

**Comment by mikera** [comment]
Hi @pedrorgirardi that looks like the expander macro for `when-not`.

What needs to happen is reading the metadata from the core environment for the Symbol `when-not`. Probably the sandbox needs to:
- Check the source to see if it a symbol after reading but *before* evaluating it
- If it is a single Symbol, check for doc metadata
- Either way, still evaluate to get the result, but if there was metadata display this instead of the raw result

I think that handles all cases?

**Comment by pedrorgirardi** [comment]
Right! That makes sense @mikera .
