### ISSUE TITLE
Rework the Teams Page

### ISSUE THREAD

**Issue by kopcho** [Convex-Dev/convex-web#235]
Remove the current photos and replace with these: https://drive.google.com/drive/folders/1g2kXlEqgThXOPbQ_RUOGFkY1ajKPYDFv?usp=share_link

Redo the Teams Page with the Following Sub-headings:
**Key Team Members**  (not alphabetical on purpose)
Mike Anderson - Founder
Adam Helins -Technology
Dr. Leonard Anderson - Governance
Michael Borrelli - Operations
Rich Kopcho - Marketing

**Advisors** (Alphabetical)
Claire Cumming
Spencer Dobson
Tej Dosanjh
Toby Lewis
Victor Munoz
Rupert Pearson
Rodney Prescott
Kurt	Sampson
Robert Seller
Ian Staley
Tirath Virdee
Riley Wild
Christina Yan Zhang

Community Contributors (Alphabetical)
Bill Barman
Jonathan Day
Miguel Depaz
Mark Engelberg
Pedro Girardi
Isaac Johnston
Ike Mawira
John Newman
Giezi Ordonez
Alexa Au Yong

**Partners and Collaborators**
Obsidian Systems (logo in route)
Need list here

**Comment by mikera** [comment]
Specific link to People list: https://docs.google.com/spreadsheets/d/1yMhqP3IyTSI4KMDemHcIba3OO0WKhtxN/edit?usp=share_link&ouid=112483384055613781820&rtpof=true&sd=true

@pedrorgirardi
