### ISSUE TITLE
Website Update to the Design elements

### ISSUE THREAD

**Issue by kopcho** [Convex-Dev/convex-web#243]
Update the Convex website design by applying the core styling per the Figma files linked herein.  Please note we will need to collaborate with the designer on some of the images to be used once we have the basic layout ready for review prior to deployment.  

Here is the Figma file for the Convex website refresh.

https://www.figma.com/file/LNeAEbNl0aRvqtfOgAfeZk/CONVEX-Web-Refresh-(v_F)?node-id=0%3A1&t=zQmPmIyxxyKprMLo-1

Here is an embed code which Figma also generates.

<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800"
height="450"
src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FLNeAEbNl0aRvqtfOgAfeZk%2FCONVEX-Web-Refresh-(v_F)%3Fnode-id%3D0%253A1%26t%3DzQmPmIyxxyKprMLo-1"
allowfullscreen></iframe> <<iframe style="border: 1px solid rgba(0, 0,
0, 0.1);" width="800" height="450"
src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FLNeAEbNl0aRvqtfOgAfeZk%2FCONVEX-Web-Refresh-(v_F)%3Fnode-id%3D0%253A1%26t%3DzQmPmIyxxyKprMLo-1"
allowfullscreen></iframe>>

**Comment by kopcho** [comment]
1) On the Figma, there is a light blue horizontal line at the top left of the home page that is a style element for our branding.  It needs to be added to the site.
2) The above the fold (and all other) toroids need to have transparency applied ~15% so they do not clash with the text.
3) The pages: Use Cases, Ecosystem, Team, About, need the text to be turned to our blue color, they are black right now (in the Figma).
4) All the toroids for the website are here: https://drive.google.com/drive/folders/1p_BmmrXdfXnWva1-X1vTiUOHiifcj5Cw?usp=sharing
5)  We need to add the following pages Trademark Use, Privacy Policy, Terms of Use - I'll create a separate issue for these!
6) On footer, the whole design in Figma needs to be implemented.  
7) On the footer "Subscribe to Convex Via Email" (as seen on Figma) when we have the tech to support gathering emails, it should read: Keep up to date with Convex news and features (replacing the lorem).

**Comment by pedrorgirardi** [comment]
Thanks @kopcho !
